services:
  db:
    image: postgres:${POSTGRES_VERSION:-15}
    container_name: teamfoundry-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build:
      context: ./backend
    container_name: teamfoundry-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST:-db}:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
    container_name: teamfoundry-frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    driver: bridge
